### ISSUE TITLE
required patch 0955 described is not available on site

### ISSUE THREAD

**Issue by mvanholsteijn** [wso2/private-paas-cartridges#25]
Hi, I am trying to following the installation guide but the required patch 0955 is not available from this site. 

Can you give me a URL to download it?

Cheers,

Mark

**Comment by anuruddhal** [comment]
Hi Mark,

Can you point me to the reference to patch 0995 in documentation?
AFAIK there is no requirement to include patch 0995.

Regards,
Anuruddha

**Comment by pubudu538** [comment]
Hi Mark,

You can download security patches from [1]. We will update the readme files with this link.

[1] - http://wso2.com/security-patch-releases

**Comment by mvanholsteijn** [comment]
Patch 0955 is referred to here https://github.com/wso2/private-paas-cartridges/blob/master/wso2is/5.0.0/template-module/README.md

**Comment by imesh** [comment]
Patch 0955 can be on the following page under security patches:
http://wso2.com/api-management/try-it/
