### ISSUE TITLE
Cannot create Docker image

### ISSUE THREAD

**Issue by AndreDuarte00** [wso2/private-paas-cartridges#30]
Hello,

We are trying to deploy the WSO2 API Manager in a Docker container by following the instructions provided here: https://github.com/wso2/private-paas-cartridges/tree/v4.1.1/wso2am/1.9.1/docker. Although when the `build.sh` Command finishes, and it starts to build the Docker image, Docker can't seem to download the base image from the server. It gives the following error:
`Step 1 : FROM wso2/base-image:4.1.3`
`Pulling repository docker.io/wso2/base-image`
`Error: image wso2/base-image:4.1.3 not found`

Thank you,
Best regards

**Comment by chamilad** [comment]
WSO2 Product Docker images for WSO2 Private PaaS uses wso2/base-image as the basis. This image has to be built before building the product image (which is mentioned in the root README [1]).

Please follow the README at [2] to build the base image and then build APIM 1.9.1 Dockerfile.

[1] - https://github.com/wso2/private-paas-cartridges/blob/master/README.md
[2] - https://github.com/wso2/private-paas-cartridges/tree/v4.1.1/common/docker/base-image
